# Generated by Django 5.2.4 on 2025-07-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
